# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-08-18 11:22
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Chmielenie',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('weight', models.FloatField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Dodatki',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('weight', models.FloatField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Drożdże',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(blank=True, choices=[('starter płynne', 'starter płynne'), ('suche', 'suche'), ('gęstwa', 'gęstwa')], max_length=20, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Hop',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('variety', models.CharField(max_length=50)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Malt',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('variety', models.CharField(max_length=50)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Other',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('variety', models.CharField(max_length=50)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Recipe',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('style', models.CharField(max_length=100)),
                ('text', models.TextField()),
                ('brew_date', models.DateField()),
                ('foto', models.ImageField(upload_to='')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('hops', models.ManyToManyField(through='recipes.Chmielenie', to='recipes.Hop')),
            ],
        ),
        migrations.CreateModel(
            name='Yeast',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('variety', models.CharField(max_length=50)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Zasyp',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('weight', models.FloatField(blank=True, null=True)),
                ('malt', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='recipes.Malt')),
                ('recipe', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='recipes.Recipe')),
            ],
        ),
        migrations.AddField(
            model_name='recipe',
            name='malts',
            field=models.ManyToManyField(through='recipes.Zasyp', to='recipes.Malt'),
        ),
        migrations.AddField(
            model_name='recipe',
            name='other',
            field=models.ManyToManyField(through='recipes.Dodatki', to='recipes.Other'),
        ),
        migrations.AddField(
            model_name='recipe',
            name='yeast',
            field=models.ManyToManyField(through='recipes.Drożdże', to='recipes.Yeast'),
        ),
        migrations.AddField(
            model_name='drożdże',
            name='recipe',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='recipes.Recipe'),
        ),
        migrations.AddField(
            model_name='drożdże',
            name='yeast',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='recipes.Yeast'),
        ),
        migrations.AddField(
            model_name='dodatki',
            name='other',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='recipes.Other'),
        ),
        migrations.AddField(
            model_name='dodatki',
            name='recipe',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='recipes.Recipe'),
        ),
        migrations.AddField(
            model_name='chmielenie',
            name='hop',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='recipes.Hop'),
        ),
        migrations.AddField(
            model_name='chmielenie',
            name='recipe',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='recipes.Recipe'),
        ),
    ]
