# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-09-05 10:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipe',
            name='ABV',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='recipe',
            name='IBU',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='recipe',
            name='OG',
            field=models.FloatField(default=0),
        ),
    ]
