# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-12-17 17:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0003_auto_20160907_1245'),
    ]

    operations = [
        migrations.AddField(
            model_name='hop',
            name='weight',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='malt',
            name='weight',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='other',
            name='weight',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='yeast',
            name='weight',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='recipe',
            name='foto',
            field=models.ImageField(blank=True, upload_to='static/pictures/'),
        ),
    ]
