# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-12-22 20:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0005_remove_zasyp_weight'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='hop',
            name='weight',
        ),
        migrations.RemoveField(
            model_name='malt',
            name='weight',
        ),
        migrations.RemoveField(
            model_name='other',
            name='weight',
        ),
        migrations.RemoveField(
            model_name='yeast',
            name='weight',
        ),
        migrations.AddField(
            model_name='zasyp',
            name='weight',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
